### PR TITLE
New 2023 outputs using an RFC 7093 SKID generation method

### PR DESCRIPTION
**Pull request by pgporada**
Related boulder PR https://github.com/letsencrypt/boulder/pull/7179

- - - -

[RFC 7093 section 2 option 1](https://datatracker.ietf.org/doc/html/rfc7093#section-2) provides a methods for generating a truncated SHA256 hash for the Subject Key Identifier field in accordance with Baseline Requirement [section 7.1.2.11.4 Subject Key Identifier](https://github.com/cabforum/servercert/blob/90a98dc7c1131eaab01af411968aa7330d315b9b/docs/BR.md#712114-subject-key-identifier). 

>    [RFC5280] specifies two examples for generating key identifiers from
>    public keys.  Four additional mechanisms are as follows:
> 
>    1) The keyIdentifier is composed of the leftmost 160-bits of the
>       SHA-256 hash of the value of the BIT STRING subjectPublicKey
>       (excluding the tag, length, and number of unused bits).

The related [RFC 5280 section 4.2.1.2](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.2) states:
>   For CA certificates, subject key identifiers SHOULD be derived from
>   the public key or a method that generates unique values.  Two common
>   methods for generating key identifiers from the public key are:
>   ...
>   Other methods of generating unique numbers are also acceptable.

### CODE REVIEW

**Review by aarongable — COMMENTED** [review]
I've confirmed that the intermediate SKIDs are now 160 bits, and that the SKIDs match between the ECDSA intermediates and their cross-signs.

But it looks like the AKIDs have also changed, while the files representing the CAs these were issued from haven't changed at all. I think that means that the files representing the roots were regenerated, but not checked in. Why were these files not regenerated from the already-checked-in roots?

**Comment by pgporada** [comment]
Ach 🤦🏼‍♂️ 
You're right, I only copied from the 2023 ceremony directory into the 2023 output directory. I'll whip up a script to do this instead.

**Comment by aarongable** [comment]
Honestly I think this is a pretty good argument for checking in the private keys, too. Even though that's generally a bad idea, and I think github will yell at us, and we'll have to add them to the boulder blocked keys table. That way we don't have to regenerate _everything_ every time, and could instead start from the results of previous ceremonies and work forward from there. But that's a thing for a future change, imo.

**Review by aarongable — APPROVED** [review]
LGTM. Only the serials, keys, SKIDs, AKIDs, and signatures have changed. The SKIDs and AKIDs match where they need to. And the 2023 ceremony SKIDs are now 160 bits.

**Comment by pgporada** [comment]
> add them to the boulder blocked keys table

That is precisely why I haven't done it. 👍🏼

**Pull request merged**
